### ISSUE TITLE
windows11 怎么开mahjong-helper.exe

### ISSUE THREAD

**Issue by yxwoaiy** [moxcomic/majsoul-ex#6]
windows11 怎么开mahjong-helper.exe
code-zh.js 扔到replace
config.json  里面也打开"no_cache_codejs": true,"mahjong_helper": true,

但就是没用好气

**Comment by moxcomic** [comment]
1. 将code-zh.js改为code.js
2. F12打开控制台
3. 在Console里输入clearAllCache()
4. 重启软件

**Comment by yxwoaiy** [comment]
> 1. 将code-zh.js改为code.js
> 2. F12打开控制台
> 3. 在Console里输入clearAllCache()
> 4. 重启软件

成功了  现在就是金钱和辉玉显示不正常。。
